
-- create
CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  adsress TEXT NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Max', 30, 'MOSKVA');
INSERT INTO EMPLOYEE VALUES (0002, 'Nasty', 29, 'MOSKVA');
INSERT INTO EMPLOYEE VALUES (0003, 'Lena', 45, 'ZVENIGOROD');
INSERT INTO EMPLOYEE VALUES (0004, 'KolY', 18, 'MOSKVA');
INSERT INTO EMPLOYEE VALUES (0005, 'Janat', 70, 'KOKSHETAU');

-- fetch 
SELECT NAME FROM EMPLOYEE WHERE age >17 AND age < 30 AND adsress = 'MOSKVA'